services:
  mysql:
    container_name: 'mysqlcontainer'
    image: 'mysql:latest'
    ports:
      - 3312:3306
    environment:
      - 'MYSQL_DATABASE=tp3database'
      - 'MYSQL_PASSWORD=Numsey@Password!'
      - 'MYSQL_ROOT_PASSWORD=Numsey@Password!!'
      - 'MYSQL_USER=myuser'